services:
  app:
    build: ./api-sas
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: 172.20.0.3
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: SaSTt1_GeeGie2p
      CORS_ORIGIN: http://intproj22.sit.kmutt.ac.th/tt1
    networks:
      sas_network:
        ipv4_address: 172.20.0.2
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: SaSTt1_GeeGie2p
      MYSQL_DATABASE: announcementsystem
      MYSQL_USER: dev
      MYSQL_PASSWORD: SaSTt1_GeeGie2p
      LANG: en_US.UTF-8
    networks:
      sas_network:
        ipv4_address: 172.20.0.3
    ports:
      - "3306:3306"
    volumes:
      - ./db/sas_script_create.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/sysadmin/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
  front:
    image: front
    build:
      context: ./front-sas
      dockerfile: ../frontDockerfile
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  sas_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16